SHOW CREATE TABLE `bdproyectostock`.`venta`;
DESCRIBE `bdproyectostock`.`venta`;
SHOW INDEX FROM `bdproyectostock`.`venta`;
SELECT 
    TABLE_NAME, 
    COLUMN_NAME, 
    CONSTRAINT_NAME, 
    REFERENCED_TABLE_NAME, 
    REFERENCED_COLUMN_NAME 
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
WHERE
    TABLE_NAME = 'venta' 
    AND TABLE_SCHEMA = 'bdproyectostock'
    AND REFERENCED_TABLE_NAME IS NOT NULL;
